version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "${IMAGE_URI}"
        LoadBalancerInfo:
          ContainerName: "api"
          ContainerPort: 8080
